name: publish-app
on:
  workflow_dispatch:
    inputs:
      level:
        description: '<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease'
        required: true
        default: 'patch'
      tag:
        description: 'The tag to publish to.'
        required: false
        default: 'latest'
jobs:
  checkout:
    name: checkout
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
        working-directory: ${{env.WORKING_DIR}}
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "@apoorva2405"
          npm config list
        working-directory: ${{env.WORKING_DIR}}
      - run: cd ./packages/uxp-devtools-app && yarn install
        working-directory: ${{env.WORKING_DIR}}
      - run: cd ./packages/uxp-devtools-app && yarn cdt-custom-setup &&  node scripts/installAppDeps.js
      - run: cd ./packages/uxp-devtools-app && yarn package 
        working-directory: ${{env.WORKING_DIR}}
      # - run: cd ./packages/uxp-devtools-app && zip dist.zip dist -r -m
      #   working-directory: ${{env.WORKING_DIR}}
      - run: npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN && npm publish --access public
        working-directory: ${{env.WORKING_DIR}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          WORKING_DIR: ./packages/uxp-devtools-app
