name: version-bump-publish
on:
  workflow_dispatch:
    inputs:
      level:
        description: '<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease'
        required: true
        default: 'patch'
      tag:
        description: 'The tag to publish to.'
        required: false
        default: 'latest'
jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm install
          npm test
      - name: publish all packages
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "<@OWNER>"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          access: 'public'
